# Tirgul 7- Decision Tree and Random Forest

In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
from sklearn import tree
from sklearn.tree import DecisionTreeRegressor
from sklearn.tree import DecisionTreeClassifier

melbourne_file_path = 'melb_data.csv'
melbourne_data = pd.read_csv(melbourne_file_path) 
print("Data Frame Lenght: {}".format(len(melbourne_data)))
melbourne_data.head()

Data Frame Lenght: 13580


Suburb           Address  Rooms Type      Price Method SellerG  \
0  Abbotsford      85 Turner St      2    h  1480000.0      S  Biggin   
1  Abbotsford   25 Bloomburg St      2    h  1035000.0      S  Biggin   
2  Abbotsford      5 Charles St      3    h  1465000.0     SP  Biggin   
3  Abbotsford  40 Federation La      3    h   850000.0     PI  Biggin   
4  Abbotsford       55a Park St      4    h  1600000.0     VB  Nelson   

        Date  Distance  Postcode  ...  Bathroom  Car  Landsize  BuildingArea  \
0  3/12/2016       2.5    3067.0  ...       1.0  1.0     202.0           NaN   
1  4/02/2016       2.5    3067.0  ...       1.0  0.0     156.0          79.0   
2  4/03/2017       2.5    3067.0  ...       2.0  0.0     134.0         150.0   
3  4/03/2017       2.5    3067.0  ...       2.0  1.0      94.0           NaN   
4  4/06/2016       2.5    3067.0  ...       1.0  2.0     120.0         142.0   

   YearBuilt  CouncilArea Lattitude  Longtitude             Regionname  \
0        NaN        Yarra  -37.7996    144.9984  Northern Metropolitan   
1     1900.0        Yarra  -37.8079    144.9934  Northern Metropolitan   
2     1900.0        Yarra  -37.8093    144.9944  Northern Metropolitan   
3        NaN        Yarra  -37.7969    144.9969  Northern Metropolitan   
4     2014.0        Yarra  -37.8072    144.9941  Northern Metropolitan   

  Propertycount  
0        4019.0  
1        4019.0  
2        4019.0  
3        4019.0  
4        4019.0  

[5 rows x 21 columns]

## Drop NA
Make sure to delete entries (rows) with _null_ values

In [2]:
# drop na values
melbourne_data = melbourne_data.dropna(axis=0)

## Select features

In [3]:
# Aquire data from multiple collumns
melbourne_features = ['Rooms', 'Bathroom', 'Landsize', 'Lattitude', 'Longtitude']
X = melbourne_data[melbourne_features]
y = melbourne_data['Price']

In [5]:
X.head()
y.head()

1    1035000.0
2    1465000.0
4    1600000.0
6    1876000.0
7    1636000.0
Name: Price, dtype: float64

## Train/Test split

In [6]:
# Spliting the data to train and test set.  Specify a number for random_state to ensure same results each run
X_train, X_test, y_train, y_test = sk.model_selection.train_test_split(X, y, test_size=0.2, random_state=42) 

$\sqrt{\frac{1}{N}\sum_i^N{(out_i-lbl_i)^2}}$

In [7]:
def acc(out,lbl):
    return (out==lbl).mean()

def rmse(a,b):
    return np.sqrt(np.square(a-b).mean())

## Building the tree

In [8]:
from sklearn.tree import DecisionTreeRegressor

# Define model. Specify a number for random_state to ensure same results each run
melbourne_model = DecisionTreeRegressor(random_state=42)

# Fit model
melbourne_model.fit(X_train, y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=42, splitter='best')

In [13]:
type(y_test.head().values)

numpy.ndarray

In [9]:
print("Making predictions for the following 5 houses:")
print(y_test.head().values)

print("The predictions are")
test_pred = melbourne_model.predict(X_test.head())
print(test_pred)

Making predictions for the following 5 houses:
[ 660000.  800000.  525000.  790000. 1200000.]
The predictions are
[1090000.  745000.  834500.  400000. 1320000.]


In [14]:
print("Making predictions all test houses:")
print(y_test.values)

print("The predictions are")
test_pred = melbourne_model.predict(X_test)
print(test_pred)

print("\nRMSE: {:.3f} e^3".format(rmse(y_test.values,test_pred)/1e3))

Making predictions all test houses:
[660000. 800000. 525000. ... 651000. 370000. 455000.]
The predictions are
[1090000.  745000.  834500. ...  580500.  454000.  316000.]

RMSE: 414.578 e^3


## Check the STD of the data

In [16]:
print("STD: {:.3f} e^3, Mean: {:.3f} e^3".format(y_test.std()/1e3,y_test.mean()/1e3))

import matplotlib.pyplot as plt
plt.rcParams['figure.figsize'] = [10, 5]

STD: 644.971 e^3, Mean: 1056.998 e^3


In [ ]:
(y-y_mean)/len(y)

In [ ]:
plt.hist(np.abs(y_test-y_test.mean()))

# Random Forest

In [17]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import make_regression

regr = RandomForestRegressor(n_estimators=100,max_depth=10, random_state=42)
print('Fitting model...')
regr.fit(X_train, y_train)

test_pred = regr.predict(X_test)
print("RMSE: {:.3f} e^3".format(rmse(y_test.values,test_pred)/1e3))

Fitting model...
RMSE: 309.900 e^3
