# Trigul 2
 A deeper dive into *Pandas* and *Numpy*

In [30]:
# read file using pandas
# pandas is a fast, powerful, flexible and easy to use open source data analysis in python
import pandas as pd
data = pd.read_csv('titanic_short.csv')
### The data read is of type dataframe, which is a 2D data structure where columns can be of different types
data

pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
12    1st         1      NaN  female
13    1st         1      NaN    male
14    1st         0      NaN    male
15    1st         1  50.0000  female
16    1st         0  24.0000    male
17    1st         0  36.0000    male
18    1st         1  37.0000    male
19    1st         1      NaN  female
20    1st         1  26.0000    male
21    1st         0  25.0000    male
22    1st         1      NaN    male
23    1st         1  19.0000  female
24    1st         1  28.0000    male
25    1st         0      NaN    male
26    1st         1  39.0000    male
27    1st         1  30.0000  female
28    1st         1  58.0000  female
29    1st         0      NaN    male

[Tutorial for python data frames](https://stackabuse.com/beginners-tutorial-on-the-pandas-python-library/)

In [31]:
# print using python system print
print(data)

   pclass  survived      age     sex
0     1st         1  29.0000  female
1     1st         0   2.0000  female
2     1st         0  30.0000    male
3     1st         0  25.0000  female
4     1st         1   0.9167    male
5     1st         1  47.0000    male
6     1st         1  63.0000  female
7     1st         0  39.0000    male
8     1st         1  58.0000  female
9     1st         0  71.0000    male
10    1st         0  47.0000    male
11    1st         1  19.0000  female
12    1st         1      NaN  female
13    1st         1      NaN    male
14    1st         0      NaN    male
15    1st         1  50.0000  female
16    1st         0  24.0000    male
17    1st         0  36.0000    male
18    1st         1  37.0000    male
19    1st         1      NaN  female
20    1st         1  26.0000    male
21    1st         0  25.0000    male
22    1st         1      NaN    male
23    1st         1  19.0000  female
24    1st         1  28.0000    male
25    1st         0      NaN    male
2

In [32]:
data.head(9)# we can set the number of first rows to be displayed.
# guess what is the commmand for the tail

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male
5    1st         1  47.0000    male
6    1st         1  63.0000  female
7    1st         0  39.0000    male
8    1st         1  58.0000  female

In [34]:
# Same goes for tail
data.tail(10)

pclass  survived   age     sex
20    1st         1  26.0    male
21    1st         0  25.0    male
22    1st         1   NaN    male
23    1st         1  19.0  female
24    1st         1  28.0    male
25    1st         0   NaN    male
26    1st         1  39.0    male
27    1st         1  30.0  female
28    1st         1  58.0  female
29    1st         0   NaN    male

#### Setting values of specific cells:

In [35]:
data.head()

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         0  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male

In [39]:
data.loc[1:4:2,'survived']=0
data.head()

pclass  survived      age     sex
0    1st         1  29.0000  female
1    1st         0   2.0000  female
2    1st         1  30.0000    male
3    1st         0  25.0000  female
4    1st         1   0.9167    male

### Self excercise: Suggest how to display only survivors (denoted by 1)


In [41]:
sur_df = data['sex'] == 'female'
data[sur_df]

pclass  survived   age     sex
0     1st         1  29.0  female
1     1st         0   2.0  female
3     1st         0  25.0  female
6     1st         1  63.0  female
8     1st         1  58.0  female
11    1st         1  19.0  female
12    1st         1   NaN  female
15    1st         1  50.0  female
19    1st         1   NaN  female
23    1st         1  19.0  female
27    1st         1  30.0  female
28    1st         1  58.0  female

### Self excercise: Suggest how to display only females gender

In [42]:
data[data['sex']=='female']

pclass  survived   age     sex
0     1st         1  29.0  female
1     1st         0   2.0  female
3     1st         0  25.0  female
6     1st         1  63.0  female
8     1st         1  58.0  female
11    1st         1  19.0  female
12    1st         1   NaN  female
15    1st         1  50.0  female
19    1st         1   NaN  female
23    1st         1  19.0  female
27    1st         1  30.0  female
28    1st         1  58.0  female

# Self excercise: Suggest how to display only females survivors

In [45]:
surr_idx = data['survived'] == 1    # Only survived
female_idx = data['sex']=='female'  # Only Female
data[surr_idx & female_idx]         # Select Survived and Female only!

pclass  survived   age     sex
0     1st         1  29.0  female
6     1st         1  63.0  female
8     1st         1  58.0  female
11    1st         1  19.0  female
12    1st         1   NaN  female
15    1st         1  50.0  female
19    1st         1   NaN  female
23    1st         1  19.0  female
27    1st         1  30.0  female
28    1st         1  58.0  female

In [52]:
#### Select rows that have a null value at the 'age' column
data_age = data['age']
has_age = pd.isnull(data_age)
data[has_age]

pclass  survived  age     sex
12    1st         1  NaN  female
13    1st         1  NaN    male
14    1st         0  NaN    male
19    1st         1  NaN  female
22    1st         1  NaN    male
25    1st         0  NaN    male
29    1st         0  NaN    male

#### Number of rows and collumns by shape attribute:

In [53]:
data.shape # First number is the rows, second is columns

(30, 4)

#### Get more information such as the column names by info() method

In [55]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   pclass    30 non-null     object 
 1   survived  30 non-null     int64  
 2   age       23 non-null     float64
 3   sex       30 non-null     object 
dtypes: float64(1), int64(1), object(2)
memory usage: 1.1+ KB


## Numpy
Math, matrices and much more, this is where the fun begins..

[Numpy official docs](https://numpy.org/doc/stable/reference/index.html)

In [74]:
import numpy as np
lst = [1, 2, 3, 4, 5]
arr = np.array([
    [1,2,3,4],
    [11,22,33,44]
])
arr.shape
# arr1 = np.array([
#     [11,21,31,1],
#     [11,21,31,1]
# ])
# arr * arr1     # Matrix bit-wise multiplication
# print(arr*arr) # Equal to np.square(arr)
# arr.dot(arr.T) # Matrix multiplicaion with Transpose on 'arr'

(2, 4)

#### Vector multiplication (AKA dot producdt)

In [75]:
print("arr.dot(arr)\t=",arr.dot(arr1.T))
# # or by 
print("arr@arr\t\t=",arr @ arr1.T)    # This is the new way!


arr.dot(arr)	= [[ 150  150]
 [1650 1650]]
arr@arr		= [[ 150  150]
 [1650 1650]]


In [79]:
# create ones matrix of specific size:
np.ones((2,3))
arr.shape
# h,w = arr.shape
# np.ones((h,w))
# np.ones_like(arr)

(2, 4)

In [60]:
# self excercise: create zeros matrix of specific size:




In [62]:
# we can create any constant array
c = np.full((2,2), 7)
np.ones((2,2)) * 7

array([[7., 7.],
       [7., 7.]])

In [63]:
d = np.eye(5)
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [64]:
# self excercise: create a 3X3 matrix where digonal has value of 8






##### Random matrix

In [66]:
e = np.random.random((2,4)) 
e = np.random.randint(0,10,(2,4)) 
print(e)

[[3 2 4 0]
 [3 2 3 5]]


### Self learning at home:
+ 1. Read the tutorials in links
+ 2. Write a NumPy program to test whether none of the elements of a given array is zero (create a sample array).

In [80]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
